// app/api/invitees/route.tsx
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma"; // Adjust the path if needed

// GET all invitees (including their guest records)
export async function GET() {
  try {
    // Update the query to include guestsList
    const invitees = await prisma.invitee.findMany({
      include: { guestsList: true }, // Ensure guestsList is included
    });
    return NextResponse.json(invitees);
  } catch (error) {
    console.error("GET invitees error:", error);
    return new NextResponse("Error fetching invitees", { status: 500 });
  }
}

// Create a new invitee
export async function POST(req: NextRequest) {
  try {
    const {
      name,
      email,
      guests,
      isAttending,
      maxInvites,
      dietaryRestrictions,
      accessibilityInfo,
      comments,
      songRequests,
    } = await req.json();

    // Basic checks for required fields
    if (!name || !email || guests === undefined) {
      return new NextResponse("Missing required fields: name, email, and guests are required.", { status: 400 });
    }

    let validMaxInvites = 0;
    if (typeof maxInvites === "number") {
      validMaxInvites = maxInvites;
    } else if (maxInvites === undefined) {
      // Default maxInvites to 0 if not provided, or handle as an error if it's strictly required
      validMaxInvites = 0; // Or return error: return new NextResponse("Invalid 'maxInvites' field", { status: 400 });
    } else {
      return new NextResponse("Invalid 'maxInvites' field type. Must be a number.", { status: 400 });
    }

    const newInvitee = await prisma.invitee.create({
      data: {
        name,
        email,
        guests, // This should be the initial number of guests confirmed/expected for the party
        isAttending, // This can be null initially
        maxInvites: validMaxInvites, // Max allowed for this party
        dietaryRestrictions: dietaryRestrictions ?? null,
        accessibilityInfo: accessibilityInfo ?? null,
        comments: comments ?? null,
        songRequests: songRequests ?? null,
        // token is auto-generated by Prisma schema's @default(uuid())
        // createdAt is auto-generated by Prisma schema's @default(now())
        // respondedAt, emailOpenedAt, emailSentAt will be null initially
      },
    });

    return NextResponse.json(newInvitee);
  } catch (error) {
    console.error("POST invitees error:", error);
    // Provide more specific error for unique constraint violation if possible
    if (error instanceof Error && 'code' in error && (error as { code?: string }).code === 'P2002') {
        // P2002 is Prisma's unique constraint violation code (e.g., for email or token)
        return new NextResponse("Error creating invitee: A record with this email or token already exists.", { status: 409 }); // 409 Conflict
    }
    return new NextResponse("Error creating invitee", { status: 500 });
  }
}

// Delete an invitee by ID
export async function DELETE(req: NextRequest) {
  try {
    const { id } = await req.json();

    if (!id || typeof id !== "number") {
      return new NextResponse("Invalid or missing ID. ID must be a number.", { status: 400 });
    }

    // MODIFICATION START: Delete associated guests first, then the invitee, within a transaction
    await prisma.$transaction(async (tx) => {
      // Step 1: Delete all Guest records associated with this Invitee
      await tx.guest.deleteMany({
        where: { inviteeId: id },
      });

      // Step 2: Delete the Invitee record
      await tx.invitee.delete({
        where: { id },
      });
    });
    // MODIFICATION END

    return new NextResponse("Invitee and associated guests deleted successfully", { status: 200 });
  } catch (error) {
    console.error("DELETE invitee error:", error);
    // Check for specific Prisma errors, e.g., if the invitee to delete was not found
    if (error instanceof Error && 'code' in error && (error as { code?: string }).code === 'P2025') {
        // P2025: Record to delete not found
        return new NextResponse("Error deleting invitee: Record not found.", { status: 404 });
    }
    return new NextResponse("Error deleting invitee", { status: 500 });
  }
}
